version: '3.9'
services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile.django
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - celery_worker
    # env_file:
    #   - .env
    environment:
      - DJANGO_SETTINGS_MODULE=billwise.settings
      - CELERY_BROKER=pyamqp://guest@rabbitmq:5672//
      - IN_DOCKER=1
      - SITE_ID=1
    networks:
      - backend-network
    command: python manage.py runserver 0.0.0.0:8000

  nextjs:
    build:
      # context: ./frontend
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/frontend
    #   - /frontend/node_modules
    #   - /frontend/.next
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    # env_file:
    #   - ./frontend/.env.local
    environment:
      NEXTAUTH_BACKEND_URL: http://django:8000/api/
      NEXT_PUBLIC_URL: http://127.0.0.1:8000/api/
      NEXTAUTH_URL: http://127.0.0.1:3000/
    networks:
      - backend-network

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: billwise_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend-network

  rabbitmq:
    image: "rabbitmq:3.12-alpine"
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ
    networks:
      - backend-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - rabbitmq
      - postgres
    # env_file:
    #   - .env
    networks:
      - backend-network
    ports: []
    command: celery -A billwise worker -l INFO -c 4

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - django
      - rabbitmq
    # env_file:
    #   - .env
    networks:
      - backend-network
    command: celery -A billwise beat -l info

  flower:
    image: mher/flower
    depends_on:
      - celery_worker
      - celery_beat
    command: celery flower
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672//
      - FLOWER_PORT=5555
    ports:
    - "5555:5555"
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge