FROM koyeb/docker-compose

COPY . /app

# Install Git
RUN apk add --no-cache git

# Run Docker Compose using the compose file in /app
# CMD ["docker-compose", "-f", "/app/docker-compose.yaml", "--verbose","up"]
CMD ["docker-compose", "-f", "/app/docker-compose.yaml", "--verbose", "up", "django", "postgres", "rabbitmq"]