version: '3.9'
services:
  django: &django
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - celery_worker
    environment:
      - DJANGO_SETTINGS_MODULE=billwise.settings
      - CELERY_BROKER=pyamqp://guest@rabbitmq:5672//
      - IN_DOCKER=1
    command: python manage.py runserver 0.0.0.0:8000

  nextjs:
    container_name: nextjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
    ports:
      - "3000:3000"

  db:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_DB: billwise_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.12-alpine"
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ

  celery_worker:
    <<: *django 
    container_name: celery_worker
    build:
      context: .
    depends_on:
      - rabbitmq
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=billwise.settings
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672//
    ports: []
    command: celery -A billwise worker -l INFO

  celery_beat:
    container_name: celery_beat
    build:
      context: .
    depends_on:
      - django
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=billwise.settings
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672//
    command: celery -A billwise beat -l info

  flower:
    image: mher/flower
    container_name: flower
    depends_on:
      - celery_worker
    command: celery flower
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq:5672//
      - FLOWER_PORT=5555
    ports:
    - "5555:5555"

volumes:
  postgres_data:
