# Generated by Django 4.2.2 on 2023-06-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='media',
        ),
        migrations.AddField(
            model_name='supplier',
            name='media',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.media'),
            preserve_default=False,
        ),
    ]
