# Generated by Django 4.2.2 on 2023-07-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_supplier_media_supplier_media'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Category',
        ),
    ]
