# Generated by Django 4.2.2 on 2023-10-25 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230930_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='supplier',
        ),
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='consumption_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
