# Generated by Django 4.2.2 on 2023-11-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_invoice_bank_account_number_invoice_transfer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_sync',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja'),
        ),
    ]
