# Generated by Django 4.2.2 on 2024-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_account_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
